set_property SRC_FILE_INFO {cfile:C:/Users/jmao/Desktop/j_mao_lab4/j_mao_lab4.srcs/constrs_1/new/my_circuit.xdc rfile:../../../j_mao_lab4.srcs/constrs_1/new/my_circuit.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {a}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {b}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {c}]
