# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jmao/Desktop/j_mao_lab4/j_mao_lab4.cache/wt [current_project]
set_property parent.project_path C:/Users/jmao/Desktop/j_mao_lab4/j_mao_lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/jmao/Desktop/j_mao_lab4/j_mao_lab4.srcs/sources_1/new/my_circuit.v
read_xdc C:/Users/jmao/Desktop/j_mao_lab4/j_mao_lab4.srcs/constrs_1/new/my_circuit.xdc
set_property used_in_implementation false [get_files C:/Users/jmao/Desktop/j_mao_lab4/j_mao_lab4.srcs/constrs_1/new/my_circuit.xdc]

synth_design -top my_circuit -part xc7z010clg400-1
write_checkpoint -noxdef my_circuit.dcp
catch { report_utilization -file my_circuit_utilization_synth.rpt -pb my_circuit_utilization_synth.pb }
